name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install uv tox
      - name: Run Linter
        run: |
          uv run tox run -e lint

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install uv tox
      - name: Check formatting
        run: |
          uv run tox run -e format

  test:
    runs-on: ubuntu-latest
    continue-on-error: true # TODO: Remove this once the tests are passing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install uv tox
      - name: Run tests
        run: |
          uv run tox run -e test

  coverage:
    runs-on: ubuntu-latest
    continue-on-error: true # TODO: Remove this once the tests are passing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install uv tox
      - name: Run test coverage
        run: |
          uv run tox run -e coverage
